//app
export const SET_APP_PROGRESS = 'SET_APP_PROGRESS';
export const SET_APP_NOTIFICATION = 'SET_APP_NOTIFICATION';

//locale
export const SET_TRANSLATION = 'SET_TRANSLATION';

//instant
export const SET_INSTANT_HEADER = 'SET_INSTANT_HEADER';
export const SET_INSTANT_INIT = 'SET_INSTANT_INIT';
export const SHOW_INSTANT = 'SHOW_INSTANT';
export const HIDE_INSTANT = 'HIDE_INSTANT';

//user
export const SET_USER_ACCOUNT = 'SET_USER_ACCOUNT';
export const SET_USER_POSITION = 'SET_USER_POSITION';
export const SET_USER_TRACKING = 'SET_USER_TRACKING';

//places
export const SET_PLACES_NEARBY = 'SET_PLACES_NEARBY';
export const SET_PLACES_LIST = 'SET_PLACES_LIST';

//fighters
export const SET_FIGHTERS_NEARBY = 'SET_FIGHTERS_NEARBY';
export const SET_FIGHTERS_LIST = 'SET_FIGHTERS_LIST';